baseURL = "https://www.section.io/docs/"
languageCode = "en-us"
DefaultContentLanguage = "en"

title = "Section Documentation"
theme = "hugo-theme-learn"
# themesdir = "../.."

[params]
editURL = "https://github.com/section-io/docs/blob/master/content/"
noHomeIcon = false # default is false
noSearch = false # default is false
showVisitedLinks = true # default is false
# themeStyle = "theme" # overide base css
themeVariant = "section" # choose theme variant "green", "gold" , "gray", "blue" (default), or "section" (which lives at static/css/theme-section.css)
ordersectionsby = "weight" # ordersectionsby = "title"

[outputs]
home = [ "HTML", "RSS", "JSON"]


[[menu.shortcuts]]
identifier = "github"
name = "<i class='fa fa-code fa-fw'></i> GitHub repo"
url = "https://github.com/section-io/docs"
weight = 10

[[menu.shortcuts]]
identifier = "community"
name = "<i class='fa fa-camera fa-fw'></i> Community"
url = "https://community.section.io/"
weight = 15

[[menu.shortcuts]]
identifier = "homepage"
name = "<i class='fa fa-bookmark fa-fw'></i> Section Home"
url = "https://www.section.io/"
weight = 20
